FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/

ENV NPM_CONFIG_INCLUDE=dev
RUN npm ci --include=dev --workspaces --include-workspace-root
RUN npm ci -w apps/web --include=dev

COPY . .

RUN npm run -w apps/web build

EXPOSE 3000

CMD ["npm", "run", "-w", "apps/web", "start"]
