FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/

RUN npm ci --include=dev

COPY . .

RUN npm run -w apps/web build

EXPOSE 3000

CMD ["npm", "run", "-w", "apps/web", "start"]
