FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/

ENV NODE_ENV=development
ENV NPM_CONFIG_PRODUCTION=false
ENV NPM_CONFIG_INCLUDE=dev

RUN npm ci --workspaces --include-workspace-root --include=dev

COPY . .

RUN npm exec -w apps/api prisma generate -- --schema=apps/api/prisma/schema.prisma
RUN npm exec -w apps/api nest build

EXPOSE 4000

CMD ["node", "apps/api/dist/src/main.js"]
