FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/

RUN npm ci --include=dev

COPY . .

RUN npm exec -w apps/api prisma generate -- --schema=prisma/schema.prisma
RUN npm run -w apps/api build

EXPOSE 4000

CMD ["node", "apps/api/dist/src/main.js"]
